name: quizlet_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.1
  color_hex: ^0.0.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.4
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/asset/result_images/
    - lib/asset/icon/icon.png

flutter_native_splash:
  color: "#fafafa"
  image: lib/asset/icon/icon.png
  android_12: 
    image: lib/asset/icon/icon.png
  android: true
  ios: true